# Generated by Django 3.1 on 2020-08-31 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zipper', '0002_auto_20200830_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmapper',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
